/**
 * Long-form markdown bodies for seeded posts (each article is 500+ words).
 * Used by src/seed.ts — keep slugs unique and excerpts ≤ 320 chars.
 */

export type SeedArticleCategorySlug =
  | "react-js"
  | "javascript"
  | "typescript"
  | "html"
  | "css"
  | "node-js"
  | "java"
  | "php";

export type SeedArticleDef = {
  title: string;
  slug: string;
  excerpt: string;
  content: string;
  tags: string[];
  categorySlug: SeedArticleCategorySlug;
  readTimeMinutes: number;
  status: "published" | "draft";
};

export const SEED_ARTICLES: SeedArticleDef[] = [
  {
    title: "React in production: patterns that survive real teams and real traffic",
    slug: "react-in-production-patterns-for-real-teams",
    excerpt:
      "A practical tour of component boundaries, state ownership, data fetching, and performance habits that keep React apps maintainable when the codebase and user base grow.",
    categorySlug: "react-js",
    readTimeMinutes: 6,
    status: "published",
    tags: ["react", "frontend", "architecture"],
    content: [
      "# React in production: patterns that survive real teams and real traffic",
      "",
      "React is often introduced as a library for building user interfaces, but the hard part is rarely the JSX syntax. The hard part is keeping a large application understandable when dozens of engineers touch the same repository, when product requirements change weekly, and when performance regressions show up only under production traffic. This article walks through patterns that consistently help teams ship stable React applications without turning every screen into a bespoke experiment.",
      "",
      "## Clarify ownership of state early",
      "",
      "The most expensive mistakes in React codebases are usually about state placement, not about hooks versus classes. Local UI state belongs close to the component that renders the controls: open menus, transient validation messages, and animation toggles rarely need to be global. Server-derived state should live behind a clear boundary: fetch in a dedicated layer, normalize results, and render with components that do not also own caching policy. When those boundaries blur, you get subtle bugs: double fetches, stale closures, and components that re-render entire subtrees because a parent memoization broke.",
      "",
      "A useful rule is to ask who is the single writer for a piece of state. If more than one module can assign it, you need either a reducer with explicit transitions or a store with disciplined actions. If only one module writes it, keep it there and pass read-only props downward. This sounds obvious, yet many codebases accumulate prop drilling and context sprawl because every new feature adds another global flag instead of a small local model.",
      "",
      "## Composition beats inheritance, and also beats mega-components",
      "",
      "React’s component model shines when you build small pieces with explicit inputs. A page component can orchestrate layout and data requirements, but it should not implement every interaction inline. Extract lists, forms, and panels into named components even if they are not reused yet. Named components communicate intent in code review and make refactors safer because boundaries are visible.",
      "",
      "Composition also helps performance work stay localized. Memoization is not free: it adds mental overhead and can hide bugs when dependencies are wrong. Prefer splitting components so expensive subtrees naturally isolate rerenders, and only then add `useMemo` or `React.memo` where profiling shows hotspots. Production profiling regularly reveals that the biggest wins come from fewer renders and smaller update trees, not from micro-optimizations on trivial leaf nodes.",
      "",
      "## Data fetching and loading states are part of the UI contract",
      "",
      "Users experience your application as a sequence of states: loading, empty, error, success, and partial refresh. Treat those states as first-class UI concerns rather than afterthoughts bolted onto a happy path. That means consistent skeletons, actionable error messages, and idempotent retries where safe. On the engineering side, it means avoiding duplicated fetch logic scattered across effects without coordination, which is a common source of race conditions when navigations happen quickly.",
      "",
      "If you adopt a data library, commit to its idioms so the team shares one mental model. If you keep fetches manual, still centralize URL construction, auth headers, and error translation so components remain mostly declarative. Either approach can work in production; inconsistency across the codebase is what hurts most.",
      "",
      "## Testing and accessibility reinforce each other",
      "",
      "Accessible markup tends to be easier to test because roles and labels give stable selectors. Treat keyboard navigation and focus management as part of feature completion, not polish at the end. In production, accessibility fixes are often forced by compliance deadlines; building habits early avoids expensive retrofitting.",
      "",
      "## Closing thoughts",
      "",
      "React scales when teams agree on boundaries: where state lives, how data flows, and what a finished feature includes for loading and failure. The patterns above are not glamorous, but they are the ones that keep a codebase approachable after the first launch, when the real work begins.",
    ].join("\n"),
  },
  {
    title: "Modern JavaScript for application developers: modules, async control, and tooling",
    slug: "modern-javascript-modules-async-and-tooling",
    excerpt:
      "How ES modules, async patterns, and disciplined bundling choices shape maintainable JavaScript apps beyond quick scripts and tutorial snippets.",
    categorySlug: "javascript",
    readTimeMinutes: 6,
    status: "published",
    tags: ["javascript", "esm", "async"],
    content: [
      "# Modern JavaScript for application developers",
      "",
      "JavaScript’s reputation for chaos is largely historical. The language today includes a mature module system, async primitives that compose well, and a tooling ecosystem that can enforce quality at scale. Still, teams struggle because tutorials emphasize syntax while production engineering requires conventions: how to structure modules, how to model asynchronous workflows safely, and how to keep build times acceptable as repositories grow.",
      "",
      "## Modules are contracts, not just file boundaries",
      "",
      "When you export a function that mutates shared module state, you have effectively created a tiny global variable. Prefer explicit parameters and return values so callers can reason locally. Barrel files can speed imports early but often become merge-conflict magnets; be deliberate about when a barrel adds clarity versus noise.",
      "",
      "Tree shaking only helps when side effects are controlled. Avoid top-level imperative work in modules that are imported widely, because it runs whenever the module graph loads. Lazy loading routes and heavy utilities keeps initial bundles smaller and improves real-world performance on mobile networks.",
      "",
      "## Async: prefer clarity over cleverness",
      "",
      "`async` and `await` reduce callback nesting, but they do not remove failure modes. Concurrent requests need cancellation or ignore strategies when responses can arrive out of order. Retries belong behind policies: which errors are transient, what backoff looks like, and how to surface permanent failures to users without silent loops.",
      "",
      "Batching and debouncing are still relevant in UI code, especially for search inputs and resize handlers. The goal is predictable behavior under load, not minimal line count.",
      "",
      "## Tooling as team agreement",
      "",
      "Linting and formatting arguments are tedious until you see a codebase without them. Pick defaults, document exceptions, and move on. Type checking via TypeScript or JSDoc types is increasingly standard even in JavaScript-first projects because it catches whole classes of mistakes before review.",
      "",
      "Source maps and structured logging matter in production debugging. When an error fires in minified code, maps bridge the gap between what users experience and what engineers can fix. Investing early saves hours during incidents.",
      "",
      "## Practical patterns in application code",
      "",
      "Event-driven UIs benefit from explicit state machines for complex flows such as checkout or onboarding. A state machine documents which transitions are legal, which reduces the accidental `if` combinations that create unreachable paths. Even a lightweight hand-rolled machine is often clearer than five booleans named `isSubmitting`, `isDone`, `hasError`, `showModal`, and `retrying`.",
      "",
      "Immutability as a habit—not a library requirement—makes changes easier to trace. When you mutate shared arrays in place, debugging becomes archaeology: you need stack traces or heavy logging to learn who changed what. When you return new structures, diffs become obvious in tests and in Redux-style time travel when you use those tools.",
      "",
      "Internationalization and formatting deserve early hooks. Dates, numbers, and plural rules vary by locale; retrofitting `Intl` usage after shipping is painful because copy and layout assumptions creep everywhere. Centralize formatting helpers and pass locale through context or configuration rather than hardcoding assumptions in every component.",
      "",
      "Finally, performance work should be guided by measurement. The browser Performance panel, Lighthouse traces, and server-side timings each reveal different truths. Optimize the slow path users hit daily before micro-optimizing code that runs once per session.",
      "",
      "## Conclusion",
      "",
      "Strong JavaScript applications are less about clever one-liners and more about predictable structure: explicit modules, disciplined async flows, and tooling that encodes team standards. Those foundations pay off the moment the app grows past a single contributor.",
    ].join("\n"),
  },
  {
    title: "TypeScript at scale: gradual adoption, strictness, and types that earn trust",
    slug: "typescript-at-scale-gradual-adoption-and-strictness",
    excerpt:
      "A grounded approach to adopting TypeScript in existing JavaScript apps: compiler flags, boundary typing, and habits that keep types accurate instead of decorative.",
    categorySlug: "typescript",
    readTimeMinutes: 6,
    status: "published",
    tags: ["typescript", "types", "migration"],
    content: [
      "# TypeScript at scale",
      "",
      "TypeScript promises safer refactors and better editor support, yet many migrations stall because teams treat types as comments rather than as executable specifications. The difference is discipline: strict compiler settings, meaningful types at module boundaries, and incremental progress that does not block shipping.",
      "",
      "## Start with compiler truth, not wishful thinking",
      "",
      "Turning on `strict` after years of implicit `any` feels painful because it surfaces every shortcut at once. A more sustainable path is tightening in steps while preventing new debt: enable `noImplicitAny` for new directories first, or enforce stricter settings in CI for changed files only. The goal is monotonic improvement, not a heroic weekend rewrite that reopens with hundreds of merge conflicts.",
      "",
      "Generated types from OpenAPI or GraphQL schemas help APIs stay honest. Hand-written DTOs drift; generated types track server changes. Where generation is impossible, narrow types at the boundary and validate unknown input with a schema library rather than casting blindly.",
      "",
      "## Types should guide design",
      "",
      "When a function accepts twelve optional fields, the type system is telling you the API is unclear. Refactor into smaller objects or explicit variants. Union types model states well: a request is either loading, success, or error, not all booleans at once.",
      "",
      "Generics are powerful but can obscure intent for readers. Prefer readable names and constraints that express business rules, not abstract puzzles.",
      "",
      "## Tests still matter",
      "",
      "Types catch many mistakes, but not logic errors. Keep meaningful tests around domain rules and integrations. TypeScript complements tests; it does not replace them.",
      "",
      "## Library typings and DefinitelyTyped",
      "",
      "Not every dependency ships first-class types. Community typings can be excellent or stale. When typings misrepresent runtime behavior, prefer narrow wrapper functions that document the truth rather than casting everywhere. A small adapter module isolates the mismatch and gives you one place to update when the library fixes its types.",
      "",
      "Version pinning matters because type packages are not always released in lockstep with runtime packages. CI that runs `tsc --noEmit` on every pull request catches breakage early. Pair that with incremental builds and project references when monorepos grow, so developers are not waiting minutes for feedback on a one-line change.",
      "",
      "## Branding and domain modeling",
      "",
      "Branded types can separate conceptually different strings—user IDs versus organization IDs—without runtime cost. This pattern looks like ceremony until a refactor swaps two IDs in a function call and the compiler catches it instantly. Use branding sparingly for high-risk domains, not for every primitive.",
      "",
      "Discriminated unions excel at modeling events, API payloads, and UI states. Exhaustiveness checking in `switch` ensures new variants force updates across the codebase, which is exactly the safety net large teams need when enums grow over time.",
      "",
      "## Editor and CI integration",
      "",
      "Enable the TypeScript language server in the editor everyone uses, and document VS Code or JetBrains settings for consistent formatting. In CI, fail builds on type errors and on lint rules that catch floating promises or misused hooks when applicable. Fast feedback loops beat quarterly cleanup sprints.",
      "",
      "## Final notes",
      "",
      "Successful TypeScript adoption is a cultural shift: code review asks whether types reflect reality, refactors update types alongside behavior, and tooling keeps feedback fast. Under those conditions, TypeScript becomes a productivity multiplier instead of ceremony.",
    ].join("\n"),
  },
  {
    title: "Semantic HTML: structure, accessibility, and why div soup costs more than you think",
    slug: "semantic-html-structure-accessibility-and-maintainability",
    excerpt:
      "Why headings, landmarks, and meaningful elements improve SEO, assistive tech support, and long-term maintenance compared to unlabeled generic containers.",
    categorySlug: "html",
    readTimeMinutes: 6,
    status: "published",
    tags: ["html", "a11y", "semantics"],
    content: [
      "# Semantic HTML: structure, accessibility, and maintainability",
      "",
      "It is tempting to treat HTML as a thin wrapper around CSS and JavaScript, especially when design systems abstract layout. That approach works until you need predictable behavior for screen readers, search engines, and keyboard users, or until a new engineer cannot understand the page because every region is an anonymous `div`. Semantic HTML is not nostalgia; it is a contract with the platform about meaning.",
      "",
      "## Headings define an outline",
      "",
      "Heading levels create a navigable structure. Skipping levels or using headings purely for font size breaks that outline and confuses assistive technology users who jump by heading. Style with CSS; reserve `h1`–`h6` for document hierarchy.",
      "",
      "## Landmarks reduce cognitive load",
      "",
      "Elements like `header`, `nav`, `main`, and `footer` help users move quickly through repeated chrome. Combined with skip links, they make large interfaces tolerable. Without landmarks, users must tab through every control sequentially.",
      "",
      "## Forms deserve labels and clear errors",
      "",
      "Placeholders are not labels: they disappear when typing begins. Associate labels with controls using `for`/`id` pairs or wrapping. Error messages should describe how to fix the issue, not only that something failed.",
      "",
      "## Tables for tabular data",
      "",
      "Using tables for layout is an old anti-pattern; using div grids for tabular data is a modern one. When data is rows and columns, `table` with `th` scope helps everyone, including screen reader users who rely on column headers.",
      "",
      "## Media, images, and performance semantics",
      "",
      "Images need `alt` text that conveys the purpose of the image, not a filename. Decorative images should be marked appropriately so assistive technologies skip them. Responsive images with `srcset` and `sizes` reduce wasted bytes, which is itself an accessibility win on slow networks because users can complete tasks faster.",
      "",
      "Video and audio elements should include captions and transcripts where spoken content matters. Autoplay with sound is almost always hostile to users and should be avoided except in tightly controlled experiences where users explicitly opt in.",
      "",
      "## Document metadata and social sharing",
      "",
      "The `title` element and meta descriptions influence how pages appear in search results. Open Graph tags improve previews when links are shared. These details are easy to forget in single-page apps where the server returns a shell; use server rendering or careful client updates to keep metadata aligned with the current route.",
      "",
      "## Progressive enhancement still matters",
      "",
      "Not every user runs your JavaScript bundle successfully. Networks fail, extensions block scripts, and bugs ship. When HTML forms and links work without JavaScript, users can still accomplish critical tasks. Layer enhancements on top rather than assuming the bundle always executes.",
      "",
      "## Authoring workflow and content hygiene",
      "",
      "Authors should run automated accessibility checks in CI, but also manually tab through new screens with a keyboard only. Spell checking and heading outline tools catch issues robots miss. Consistent heading styles in CMS content—not visual size alone—keep pages navigable when marketing teams publish without engineers beside them.",
      "",
      "## Conclusion",
      "",
      "Semantic HTML pays dividends in accessibility, SEO, and readability. Investing a little time up front prevents expensive retrofitting when compliance or growth forces a reckoning.",
    ].join("\n"),
  },
  {
    title: "CSS layout in 2025: Grid, Flexbox, and design tokens without the chaos",
    slug: "css-layout-grid-flexbox-and-design-tokens",
    excerpt:
      "Practical guidance for responsive layouts, spacing systems, and maintainable stylesheets when your product spans many pages and contributors.",
    categorySlug: "css",
    readTimeMinutes: 6,
    status: "published",
    tags: ["css", "layout", "design-tokens"],
    content: [
      "# CSS layout in 2025: Grid, Flexbox, and design tokens",
      "",
      "CSS is not merely visual polish; it is how users experience structure, rhythm, and hierarchy. Teams that treat styling as an afterthought often accumulate inconsistent spacing, unpredictable breakpoints, and selectors so specific that every change risks regressions. A few disciplined practices keep stylesheets approachable as products mature.",
      "",
      "## Choose Grid or Flexbox with intent",
      "",
      "Flexbox excels at one-dimensional alignment: toolbars, stacks, and distributing space along a single axis. Grid excels at two-dimensional layouts: dashboards, card galleries, and complex page regions. Mixing them thoughtfully is fine; using the wrong tool for a layout usually leads to fragile negative margins and magic numbers.",
      "",
      "## Spacing scales beat ad hoc pixels",
      "",
      "A small set of spacing tokens—four to eight steps—covers most UI needs. Tokens make rhythm consistent and reduce bike-shedding in review. Pair tokens with component-level defaults so most screens never reference raw pixel values.",
      "",
      "## Responsive design is about content, not device lists",
      "",
      "Designing only for a handful of breakpoints misses reality: foldable phones, large monitors, and zoomed text all change the canvas. Fluid type, clamp-based widths, and container queries (where supported) let components adapt based on their container, not only the viewport.",
      "",
      "## Performance and specificity",
      "",
      "Large unused styles and deep selector chains slow rendering and confuse maintenance. Prefer class-based styling with predictable specificity. Co-locate styles with components in modern setups, but keep shared tokens global so the system stays coherent.",
      "",
      "## Color, contrast, and motion",
      "",
      "Design tokens should include accessible color pairs verified against WCAG contrast guidelines, not only aesthetic palettes. Dark mode needs the same rigor: toggling themes is not just inverting colors. Motion should respect `prefers-reduced-motion` for users who disable animations for vestibular comfort.",
      "",
      "Focus styles are part of your design system. Removing outlines without replacing them breaks keyboard navigation for many users. Visible, on-brand focus rings communicate state and professionalism.",
      "",
      "## Documentation and discovery",
      "",
      "Storybook or similar tools help teams discover existing components and their props. CSS documentation alongside components reduces one-off styles that duplicate spacing and typography. When designers and engineers share vocabulary—token names, grid concepts—reviews become faster and more constructive.",
      "",
      "## Print styles and export paths",
      "",
      "Some users still print articles, invoices, and receipts. Thoughtful print stylesheets remove navigation chrome, expand links to show URLs where helpful, and avoid hard clipping on wide layouts. Even if print traffic is small, the polish signals quality.",
      "",
      "## Internationalization and layout",
      "",
      "Translated strings change length dramatically; flexible layouts tolerate expansion without overlapping controls. Mirror spacing for right-to-left languages where needed, and test with real locales rather than only pseudo translations.",
      "",
      "## Component tokens and overrides",
      "",
      "Allow controlled overrides for marketing moments, but default components to tokenized styles so one-off campaigns do not fork the system irreversibly. Document how overrides escape hatches work and when designers must pair with engineering for accessibility review.",
      "",
      "## Wrapping up",
      "",
      "Maintainable CSS is a product decision: consistent tokens, appropriate layout primitives, and responsive strategies that respect content. Those choices compound into interfaces that feel intentional instead of accidental.",
    ].join("\n"),
  },
  {
    title: "Node.js services: concurrency models, error handling, and production observability",
    slug: "nodejs-services-concurrency-errors-observability",
    excerpt:
      "Building reliable HTTP APIs and workers with Node.js: the event loop, backpressure, structured errors, and logs that help you debug incidents quickly.",
    categorySlug: "node-js",
    readTimeMinutes: 6,
    status: "published",
    tags: ["nodejs", "api", "observability"],
    content: [
      "# Node.js services: concurrency, errors, and observability",
      "",
      "Node.js makes it easy to stand up an HTTP server quickly, but production services need clarity around concurrency, failure modes, and operational visibility. The event loop model is powerful yet easy to misuse when CPU-heavy tasks block I/O or when unhandled promise rejections crash processes quietly.",
      "",
      "## Respect the event loop",
      "",
      "Node shines at I/O-bound workloads. CPU-bound work belongs in worker threads, child processes, or separate services. If you parse huge JSON synchronously on every request, latency spikes under load even though CPU usage looks modest in averages.",
      "",
      "Backpressure matters for streams and database writes. Accepting unlimited inbound work without limits leads to memory growth and cascading timeouts. Apply queue limits, circuit breakers, and sensible timeouts at boundaries.",
      "",
      "## Error handling should be boring and consistent",
      "",
      "Translate internal errors into stable HTTP responses. Log rich context server-side without leaking internals to clients. For async code, ensure rejections are handled; an unhandled rejection in the wrong place can take down a pod.",
      "",
      "## Observability pays rent daily",
      "",
      "Structured logs with request IDs correlate user journeys across services. Metrics around latency percentiles reveal problems averages hide. Tracing becomes invaluable when a request touches multiple internal calls. These tools are not optional extras once you operate beyond a single machine.",
      "",
      "## Security and configuration",
      "",
      "Secrets belong in environment stores, not repositories. Validate configuration at startup so misconfiguration fails fast rather than halfway through traffic. Keep dependencies updated; supply chain issues are part of the threat model.",
      "",
      "## HTTP APIs: versioning, pagination, and idempotency",
      "",
      "Public APIs should document stability guarantees. Breaking changes belong behind versioned paths or explicit negotiation. Cursor-based pagination scales better than naive `OFFSET` for large tables, though it requires thoughtful ordering keys.",
      "",
      "Idempotent handlers for retried writes prevent duplicate charges and duplicate records when clients retry on timeouts. Use idempotency keys for sensitive operations and persist them long enough to cover realistic retry windows.",
      "",
      "## Process management and graceful shutdown",
      "",
      "Containers stop and start constantly in orchestrated environments. Handle `SIGTERM` by stopping new requests, draining in-flight work with a deadline, then closing database connections cleanly. Abrupt exits corrupt pooled connections and create thundering herds on restart.",
      "",
      "## Dependency injection in small services",
      "",
      "Even without a framework container, passing dependencies as parameters improves testability compared to modules that import singletons everywhere. Keep wiring at the composition root so route handlers stay thin and reusable utilities stay pure when possible.",
      "",
      "## Rate limiting and abuse protection",
      "",
      "Public endpoints need per-IP and per-account limits, bot detection where appropriate, and captcha or proof-of-work only as a last resort because they hurt accessibility. Log abuse patterns without storing unnecessary personal data, and document retention policies clearly.",
      "",
      "## Configuration drift and feature flags",
      "",
      "Feature flags help roll out risky changes gradually, but stale flags accumulate debt. Schedule flag retirement and enforce owners in metadata. Environment-specific config should be validated with schemas so missing keys fail in staging, not silently in production.",
      "",
      "## Conclusion",
      "",
      "Reliable Node services combine platform awareness with operational discipline: non-blocking habits, explicit error policies, and instrumentation that turns incidents into short investigations instead of week-long mysteries.",
    ].join("\n"),
  },
  {
    title: "Java backends: JVM ergonomics, Spring-style boundaries, and operational maturity",
    slug: "java-backends-jvm-ergonomics-and-spring-boundaries",
    excerpt:
      "Notes on building maintainable Java services: garbage collection tuning basics, layering, dependency injection done thoughtfully, and deployment practices that match enterprise expectations.",
    categorySlug: "java",
    readTimeMinutes: 6,
    status: "published",
    tags: ["java", "jvm", "backend"],
    content: [
      "# Java backends: JVM ergonomics and maintainable boundaries",
      "",
      "Java remains a backbone language for large organizations because the JVM offers mature tooling, strong libraries, and operational experience across decades of deployments. That does not mean every Java service is automatically stable. Success depends on how teams structure modules, manage memory and threads, and approach configuration and releases.",
      "",
      "## JVM tuning is mostly measurement",
      "",
      "Before chasing GC flags, measure allocation rates, pause times, and heap usage under representative load. Many issues trace to accidental allocation in hot paths or unbounded caches rather than obscure collector settings. Defaults have improved; understanding your workload matters more than folklore.",
      "",
      "## Architecture beats framework magic",
      "",
      "Frameworks like Spring reduce boilerplate, but they should not obscure domain logic. Keep controllers thin, services cohesive, and persistence concerns behind repositories. When everything is annotated into a single giant class, tests slow down and refactors become risky.",
      "",
      "## Transactions and consistency",
      "",
      "Declarative transactions are convenient until nested calls create surprising rollback behavior. Be explicit about transaction boundaries around use cases, especially when integrating external systems where idempotency keys matter.",
      "",
      "## Deployment and compatibility",
      "",
      "Long-term support JDK versions, reproducible builds, and clear compatibility matrices reduce surprises during upgrades. Treat dependency updates as routine maintenance, not annual fire drills.",
      "",
      "## Testing strategy for services",
      "",
      "Unit tests should cover domain rules with fast feedback. Integration tests should exercise repositories against real database engines in containers where feasible, because SQL dialect differences and transaction behavior rarely show up in mocks alone. Contract tests protect boundaries between services owned by different teams.",
      "",
      "Flaky tests erode trust; invest in deterministic fixtures, isolated time, and stable ports. Parallel test execution speeds CI but requires databases that support isolation or ephemeral instances per worker.",
      "",
      "## Observability on the JVM",
      "",
      "Micrometer-style metrics, structured logging with correlation IDs, and optional OpenTelemetry exporters align Java services with polyglot ecosystems. Thread dumps and heap histograms remain invaluable during incidents; operators should know how to capture them safely in production without pausing the world longer than necessary.",
      "",
      "## Data access and schema evolution",
      "",
      "Migration tools should be idempotent where possible and reviewed like application code. Long-running migrations need online strategies that avoid exclusive locks on busy tables. Backfills should be chunked with progress metrics so operators can pause safely if replication lag spikes.",
      "",
      "## API design for internal Java services",
      "",
      "Even internal RPC benefits from explicit error codes and timeouts. Assume partial failures: one dependency timing out should not collapse unrelated endpoints if isolation patterns like bulkheads are applied pragmatically.",
      "",
      "## Libraries and licensing hygiene",
      "",
      "Enterprise builds often require license scanning for copyleft dependencies. Automate SBOM generation and review deltas on upgrades. Keep an internal allowlist for common stacks so engineers are not blocked on counsel for every patch version.",
      "",
      "## On-call readiness",
      "",
      "Runbooks should list common failure signatures, rollback commands, and who owns downstream dependencies. Practice restores from backups periodically; untested backups are wishful thinking.",
      "",
      "## Closing",
      "",
      "Java’s strengths show when teams combine platform knowledge with clear architecture: measured JVM behavior, explicit layering, and operational practices that match the seriousness of the workloads they run.",
    ].join("\n"),
  },
  {
    title: "Modern PHP for web applications: language improvements, frameworks, and secure defaults",
    slug: "modern-php-web-apps-language-and-security",
    excerpt:
      "How PHP 8 features, mature frameworks, and disciplined input handling support serious web applications beyond legacy stereotypes.",
    categorySlug: "php",
    readTimeMinutes: 6,
    status: "published",
    tags: ["php", "security", "web"],
    content: [
      "# Modern PHP for web applications",
      "",
      "PHP’s history includes quick scripts and inconsistent frameworks, but the language and ecosystem today include strong typing features, JIT compilation in recent versions, and frameworks that encourage maintainable structure. Teams that dismiss PHP outright often miss that many high-traffic content sites and commerce platforms still run on it successfully—because operators invested in security, performance, and clear architecture.",
      "",
      "## Language features that change daily work",
      "",
      "Union types, attributes, and constructor property promotion reduce boilerplate while making intent clearer. Enums model states without stringly-typed constants scattered across files. These features do not automatically produce good design, but they remove friction when modeling domains carefully.",
      "",
      "## Frameworks as conventions",
      "",
      "Laravel, Symfony, and others provide routing, validation, and persistence patterns that teams can learn once and reuse. The risk is over-reliance on framework magic without understanding HTTP fundamentals. Engineers should still know how sessions work, how cookies are scoped, and how CSRF protections align with their deployment topology.",
      "",
      "## Security is a checklist backed by culture",
      "",
      "Parameterized queries prevent SQL injection. Context-aware escaping prevents XSS. Password hashing should use modern algorithms and per-password salts via established libraries rather than homegrown schemes. File uploads need type and size validation, storage outside the web root where appropriate, and virus scanning when threat models require it.",
      "",
      "## Performance and scaling",
      "",
      "Opcode caches and sensible autoloading matter at scale. Profiling identifies hot paths better than guessing. Horizontal scaling pushes state to databases or caches; PHP engineers should understand session affinity implications and shared storage pitfalls.",
      "",
      "## Packaging, deployment, and the request lifecycle",
      "",
      "PHP-FPM pools, worker counts, and memory limits should match workload characteristics. Too few workers creates queueing; too many increases RAM pressure and context switching. Log slow requests with enough detail to identify N+1 query patterns and expensive remote calls.",
      "",
      "Composer lock files belong in version control so production installs match CI. Private package feeds need authentication hygiene; leaked tokens in build logs are a recurring failure mode.",
      "",
      "## Interoperability and incremental modernization",
      "",
      "Many organizations integrate PHP with message queues, search engines, and payment gateways. Clear boundaries—DTOs, validation, and anti-corruption layers—keep external models from leaking across the codebase. Incremental strangler patterns let teams modernize hotspots without rewriting entire monoliths overnight.",
      "",
      "## Local development and parity",
      "",
      "Docker Compose stacks with the same database major version as production reduce surprises. Seed scripts and fixtures should be fast enough that developers run them daily. Document common footguns on Windows versus macOS paths, line endings, and file permissions for uploads.",
      "",
      "## Observability for PHP stacks",
      "",
      "Request logs should include route name, user id when authenticated, and latency buckets. Correlate PHP-FPM slow logs with application traces to distinguish database waits from CPU-bound rendering. Set alerts on error rate spikes rather than only on average latency.",
      "",
      "## Content security and headers",
      "",
      "Set strict Content-Security-Policy directives iteratively, starting in report-only mode if needed. Combine with modern cookie flags and HTTPS everywhere to reduce session fixation and downgrade attacks.",
      "",
      "## Conclusion",
      "",
      "Modern PHP is a viable choice when teams embrace current language features, lean on mature frameworks thoughtfully, and treat security and operations as first-class concerns rather than optional add-ons.",
    ].join("\n"),
  },
  {
    title: "Draft: deepening the Bun runtime notes (work in progress)",
    slug: "draft-bun-runtime-notes-work-in-progress",
    excerpt:
      "Unpublished notes comparing cold start, package manager behavior, and Node compatibility shims—placeholder draft for admin panel testing.",
    categorySlug: "javascript",
    readTimeMinutes: 5,
    status: "draft",
    tags: ["draft", "runtime", "notes"],
    content: [
      "# Draft: Bun runtime notes",
      "",
      "This document is intentionally unfinished. It exists so administrators can verify draft visibility, author-only flows, and slug reservation without exposing incomplete analysis to the public feed.",
      "",
      "Planned sections include startup latency comparisons on Windows and Linux, npm workspace compatibility, and edge cases around native addons. The final version will cite reproducible benchmarks and pin tool versions.",
      "",
      "Until then, treat every paragraph as provisional. Numbers mentioned in early drafts may be wrong on purpose to catch copy-paste errors during editing.",
      "",
      "## Placeholder outline",
      "",
      "- Benchmark methodology",
      "- HTTP server throughput under sustained connections",
      "- Compatibility matrix for common libraries",
      "- Operational guidance for logging and crash dumps",
      "",
      "## Scratch content to meet draft body length",
      "",
      "Runtimes evolve quickly. A draft gives authors space to iterate without promising stability to readers. Product teams often want previews behind authentication; blogs usually keep drafts private to the author or staff until a publication date.",
      "",
      "When this draft publishes, it will include explicit environment notes: kernel versions, CPU classes, and whether hyperthreading was enabled. Those details matter because microbenchmarks are sensitive to thermal throttling and background processes.",
      "",
      "Documentation for experimental flags should warn users about breakage between minor releases. Draft posts are a good place to capture those warnings while internal review continues.",
      "",
      "Editors should verify links, code samples, and licensing of any quoted snippets before release. Even technical blogs accumulate legal and compliance requirements when they grow.",
      "",
      "## Expanded methodology notes (draft)",
      "",
      "Cold start measurement should repeat runs and discard the first iteration where JIT and disk caches distort results. Record whether the process was warmed by a prior request within the same instance. For serverless-style deployments, include initialization of database drivers and HTTP clients because those dominate perceived latency.",
      "",
      "Package manager comparisons should pin lockfile formats and document hoisting behavior. Workspace protocols differ between tools; claiming equivalence without evidence misleads readers who operate monorepos at scale.",
      "",
      "Compatibility shims for Node APIs need explicit version targets. A table listing modules, import styles, and pass or fail under Bun with version numbers is more valuable than narrative claims. When tests fail, capture minimal reproduction repositories rather than pasting fragments without context.",
      "",
      "Operational guidance should cover signal handling, core dump configuration, and log rotation. Runtime choice affects how SRE teams page on-call; drafts should spell out ownership boundaries between application and platform teams.",
      "",
      "## Review checklist before publish",
      "",
      "Peer review for benchmarks should verify hardware thermal headroom, background services disabled, and network isolation from corporate VPN variance. Capture raw output artifacts alongside summarized tables so readers can audit methodology months later when versions change.",
      "",
      "Legal review may be required when quoting third-party benchmarks or trademarks. Keep draft disclaimers visible until sign-off. Version the article slug only if necessary to avoid breaking inbound links; prefer updating content in place when possible.",
      "",
      "## Audience and tone pass",
      "",
      "Before publishing, read aloud for clarity, remove jargon that does not serve the reader, and verify examples compile with the versions advertised. Accessibility applies to prose too: define acronyms on first use and keep sentences readable for international audiences.",
      "",
      "Thank you for testing the draft pipeline responsibly.",
    ].join("\n"),
  },
];
